logging:
  level:
    me.avo.cosmos: TRACE

SampleService:
  scheduleRate: 15000

MessageService:
  enabled: true
  scheduleRate: 12000

azure:
  cosmosdb:
    uri: http://127.0.0.1:8081/
    key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
    database: ToDoList